### ISSUE TITLE
Using Fibry to build Kafka actor system

### ISSUE THREAD

**Issue by fr33m0nk** [lucav76/Fibry#22]
Hi Luca,

Thanks for this wonderful actor library.
I am trying to use this library to build a lightweight Kafka actor system akin Alpakka Kafka.
This actor system would comprise of following three things:
- a kafka consumer consuming messages from `some topic`
- a kafka record processing fn which would produce record to be published to `another topic`
- a producer for publishing processed record to `another topic`

Apart from above, I would like to add the functionality such that:
- Kafka consumer `poll()` is called in a infinte loop (till the Kafka consumer is shutdown)
- after `poll()` method call reads records from Kafka topic, `pause()` method is called on Kafka consumer instance.
  - This would allow kafka rrecord processor to process records in its own time. This is especially vital  if processing logic takes time (e.g. call to external service, retrial with delay  due to transient failure). `poll()` after `pause()` keeps consumer group alive with Kafka brokers and they do not trigger a rebalance of the consumer group.
- Once record processor is done, it would send processed kafka records to be published to the publisher. it would then signal Kafka consumer to commit offset and fetch a new set of records from topic. 
- Once Kafka consumer receives this signal/message,
  - `commitSync()`(or `commitAsync()`) would be called on Kafka consumer for successfully processed records
  - `resume()` method would be called on Kafka consumer followed by `poll()` which would fetch records.
- Once recently fetched records are sent to record processor,  `pause()` method is called on Kafka consumer instance again.

I have tested Alpakka Kafka Java DSL. It abstracts `pause()` and `resume()` in its DSL
While it works great and is functional, the code is hard to understand especially for people unaware of various Scala Functional interfaces (e.g. Creator). I also have to pull in org.scala-lang/scala-library apart from Alpakka kafka dependencies.

I would greatly appreciate some pointers on structuring above as a ActorSystem using Fibry and actors types to be used.

**Comment by lucav76** [comment]
Hi,
Thank you for your kind words. Your project sounds very interesting, and I would like to support you on using Fibry for it.

If these threads are intended to run for long time, you might want to take advantage of the "AutoHealing" (I haven't released a version for JDK 11 yet, but I can do it soon), as that would try to "unfreeze" threads, and I found it quite useful at work (you cna check the **AutoHealingExample** file).
Not all the actors type support auto-healing, but the basic do it (and I can add support to other types if you need it).

I would stick to the basic actors (e.g. created with **ActorSystem**, using **newActor()** or **newActorWithReturn().**

If you have a lot of logic, you might want to use a **CustomActor** (but I have to add the auto healing there).

As a general rule, is not the best to have an infinite loop inside an actor, as it will prevent other messages (including the one to terminate it) and it is incompatible with auto healing; you could however make a loop sending every time a message to yourself.

If performance are not super critical, and you want to abstract a bit more you could create a special type of actors designed to publish on a Kafka topic; in this case, the users could just send a message to the actor instead of dealing with Kafka directly.

If you want to keep in touch with this project, I will try to assist you, and I will try to be faster to answer.

Regards,
Luca

**Comment by lucav76** [comment]
Ah,
to pause the consumer, if you send a message to the record processor using **sendMessageReturn**, you will automatically wait for the message to be processed.

While Fibry is designed to have actors that process different types of messages, it can become quite verbose and possibly complex, so it is better if you can just just synchronize with the return value of the message instead of processing pause() and resume(), which would most likely require an "Erlang style" actor (ReceivingActor).
